---
- name: Import postgres repo key
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgres repositories
  become: true
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present

- name: Install postgres
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  state: present
  vars:
    packages:
      postgresql-9.6

