---
- name: Check if rbenv installed
  shell: rbenv --version
  register: rbenv_check
  ignore_errors: true
    
- name: Clone rbenv
  git: 
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
  when: rbenv_check is failed
  notify:
    - refresh user shell
    
- name: Install ruby-build as plugin
  git: 
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  when: rbenv_check is failed

- name: Install ruby
  shell: rbenv install 2.3.7

- name: Set ruby 
  shell: rbenv global 2.3.7

  