---
- name: Update ubuntu packages
  become: true
  apt:
    upgrade: dist
    update_cache: true
    
- name: copy bash_additions
  template:
    src: files/bash_additions.sh
    dest: ~/.bash_additions

- name: Ensure .bashrc sources the additions
  lineinfile:
    path: ~/.bashrc
    state: present
    line: source ~/.bash_additions
    
- name: Install packages needed by other modules
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  state: present
  vars:
    packages:
      - htop
      - autoconf
      - bison 
      - build-essential 
      - libssl-dev 
      - libyaml-dev 
      - libreadline6-dev 
      - zlib1g-dev 
      - libncurses5-dev 
      - libffi-dev 
      - libgdbm5 
      - libgdbm-dev
      - libssl1.0-dev
