---
- name: Update ubuntu packages
  become: true
  apt:
    upgrade: dist
    
- name: copy bash_additions
  template:
    src: files/bash_additions.sh
    dest: ~/.bash_additions

- name: Ensure .bashrc sources the additions
  lineinfile:
    path: ~/.bashrc
    state: present
    line: source ~/.bash_additions
    


